### ISSUE TITLE
Log color is not displayed in VS Code console

### ISSUE THREAD

**Issue by apalala-dev** [chenenyu/dog#2]
All my Logs are gray using Dog instead of colored as shown in the Readme :
```
dog.d("Test Debug message");
dog.w("Test Warning message");
dog.e("Test Error message");
```

![image](https://user-images.githubusercontent.com/6177464/108718748-0f88ed80-751f-11eb-9aba-dbfdf57657a9.png)

**Comment by chenenyu** [comment]
The flutter plugin for vscode may not support ansi color.

**Comment by apalala-dev** [comment]
It's a VS Code problem apparently : https://github.com/microsoft/vscode/issues/38834
